name: insightsninja
favicon: null
layout_spectrum: 0.3636779293883592
typography_spectrum: 0.24613164318725467
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5301390215754509
  lightness: 0.2457324075512588
  saturation: 0.32714056596159935
  rhythmicContrast: 0.7730867571663111
purpose: []
