name: INSIGHTS NINJA
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24613164318725467
title: THE INSIGHTS NINJA MASTERCLASS IS IN SESSION
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fe430c'
    - '#000271'
    - '#77888f'
    - '#fe8764'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
